### ISSUE TITLE
community.modularity()

### ISSUE THREAD

**Issue by qianyizhiye** [benedekrozemberczki/M-NMF#1]
I meet a problem about community.modularity(). First, "community" is not in your requirements so I did not install it. Then I found it and install it. But there is an error that, "community" does not have attribute modularity. 

I also tried networkx.community.modularity(), but it said that:

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    create_and_run_model(args)
  File "main.py", line 13, in create_and_run_model
    model.optimize()
  File "/home/grad/yanzhong/yanzhong/NE/M-NMF/modularity_nmf.py", line 150, in optimize
    current_modularity = self.update_state(H)
  File "/home/grad/yanzhong/yanzhong/NE/M-NMF/modularity_nmf.py", line 111, in update_state
    current_modularity = nx.community.modularity()(indices,self.G)
TypeError: modularity() takes at least 2 arguments (0 given)

**Comment by benedekrozemberczki** [comment]
I will test it in an hour. Are you using the baseline dataset?

**Comment by benedekrozemberczki** [comment]
You should install this.

https://github.com/taynaud/python-louvain

If the problem persists please contact me. Modified the README.md accordingly.
