### ISSUE TITLE
AttributeError: 'MNMF' object has no attribute 'optimal_indices'

### ISSUE THREAD

**Issue by Xshelton** [benedekrozemberczki/M-NMF#3]
Hi there, I am trying to use your method in a dataset, but an error occurs. 
it's so strange that sometime this error occurs but sometimes not..(well basically when I first ran the program, there was an 'embedding.csv' document generated(not sure whether  it is well trained or not),but the second time when I ran it ,the error occurs.

Traceback (most recent call last):
  File "C:\Users\weaton\Desktop\exp\M-NMF-master_2\M-NMF-master\src\main.py", line 103, in <module>
    create_and_run_model(args)
  File "C:\Users\weaton\Desktop\exp\M-NMF-master_2\M-NMF-master\src\main.py", line 99, in create_and_run_model
    model.optimize()
  File "C:\Users\weaton\Desktop\exp\M-NMF-master_2\M-NMF-master\src\modularity_nmf.py", line 155, in optimize
    self.initiate_dump(session, feed_dict)
  File "C:\Users\weaton\Desktop\exp\M-NMF-master_2\M-NMF-master\src\modularity_nmf.py", line 125, in initiate_dump
    json_dumper(self.optimal_indices, self.args.assignment_output)
AttributeError: 'MNMF' object has no attribute 'optimal_indices'

**Comment by Xshelton** [comment]
well
the dataset is not so big, only 789nodes and 1000 edges,just wanna try your method .THX

**Comment by benedekrozemberczki** [comment]
1. Is it connected?
2. Is it indexed consecutively?

**Comment by Xshelton** [comment]
1.I made a test to see the differences between the sample dataset and mine , I found out that the sample network is fully connected ,which means that you can reach any of the node through the net.In the opposite, my network contains plenty of paried nodes(but not connnected to the main network),is that the reason why I have this error?
2.I am pretty sure that the index is consecutive

**Comment by benedekrozemberczki** [comment]
The indexing function which generates assignments is never evaluated. Essentially modularity is not improved during the runtime. Most probably your graph is super sparse and M-NMF does not really work well on it.

**Comment by Xshelton** [comment]
Because I only selected a small part from a big graph ,maybe I could do some changes to make my networks more dense. Maybe I could do some expriments to see if  M-NMF still works well  when the net are not super sparse but relative sparse.. 
Anyway thank u so much.

**Comment by benedekrozemberczki** [comment]
Simple NMF on a matrix that is the convex combination of normalized
adjacency matrix powers works well.

**Comment by Xshelton** [comment]
you mean that  I could use the simple NMF on my network using the form of adjacency matrix?
seems like a good attemptation...

**Comment by benedekrozemberczki** [comment]
1. I mean that you normalize the adjacency matrix. This is noted by A_hat
2. You calculate A_hat^2, A_hat^3 and so on up to order 5.
3. You create a tensor from this which as shape (5 x number_of_nodes x
number_of_nodes)
4. You marginalize it over the first axis. Now you have a number_of_nodes x
number_of_nodes matrix.
5. You run sparse NMF on this matrix.
6. The node matrix has k components - these are clusters. Each value of a
node vector in this matrix is a cluster membership score.

**Comment by Xshelton** [comment]
'marginalize over the first axis ' seems to be a new concept for me...
so before marginalize I get five M*M matrices 
and after marginalize I get only a M*M matrix..
is there any function in whatever package that I could directly use it for practice(I want to know how it works)?THX  :)

**Comment by benedekrozemberczki** [comment]
Numpy? Scipy?

**Comment by Xshelton** [comment]
thx..I will use numpy for a trial..thank you for your  answer..really helpful..
